import { existsSync } from 'node:fs';
import type { StorybookConfig } from '@storybook/react-vite';

// Licensed fonts (ABC Social) are git-ignored; serve them only when present.
const licensedFonts = new URL('../fonts/licensed', import.meta.url).pathname;

const config: StorybookConfig = {
  stories: ['../stories/**/*.mdx', '../stories/**/*.stories.@(ts|tsx)'],
  addons: ['@storybook/addon-docs'],
  framework: { name: '@storybook/react-vite', options: {} },
  // Generated by `npm run build:tokens` (runs before `storybook`).
  staticDirs: [
    { from: '../build/css', to: '/css' },
    ...(existsSync(licensedFonts) ? [{ from: '../fonts/licensed', to: '/fonts' }] : []),
  ],
};

export default config;
