import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Page, Section, mono, muted } from './tokens';

const meta: Meta = { title: 'Icons' };
export default meta;
type Story = StoryObj;

/** Shape written by scripts/export-icons.mjs. */
interface IconEntry {
  name: string;
  section?: string;
  code: string[];
  aliases: string[];
  note?: string;
  color?: { figma: string; css: string };
  files: ({ file: string } & Record<string, string>)[];
}

// Generated by `npm run export:icons`; empty until the first export.
const manifests = import.meta.glob<IconEntry[]>('../icons/icons.json', { eager: true, import: 'default' });
const icons = Object.values(manifests)[0] ?? [];
const svgs = import.meta.glob<string>('../icons/**/*.svg', { eager: true, query: '?raw', import: 'default' });

const BRAND_NAMES: Record<string, string> = {
  'purple-garden': 'Purple Garden',
  kasamba: 'Kasamba',
  psiquicos: 'Psiquicos',
  'purple-ocean': 'Purple Ocean',
};

/** The variant to show for the toolbar brand and theme (brand-less sets show their first variant). */
function pick(icon: IconEntry, brand: string, theme: string) {
  const forBrand = icon.files.filter(f => !f.Brand || f.Brand === BRAND_NAMES[brand]);
  const themed = forBrand.find(f => (f.Theme ?? 'Light').toLowerCase() === theme);
  return themed ?? forBrand.find(f => !f.Theme || f.Theme === 'Light');
}

function IconCard({ icon, brand, theme }: { icon: IconEntry; brand: string; theme: string }) {
  const variant = pick(icon, brand, theme);
  const svg = variant && svgs[`../icons/${variant.file}`];
  return (
    <div
      title={[icon.name, ...icon.code, ...icon.aliases].join('\n')}
      style={{
        display: 'grid',
        gap: 8,
        justifyItems: 'center',
        padding: 12,
        borderRadius: 8,
        border: '1px solid var(--color-border-primary)',
        textAlign: 'center',
      }}
    >
      <div
        style={{
          height: 48,
          display: 'grid',
          placeItems: 'center',
          color: `var(${icon.color?.css ?? '--color-icon-primary'})`,
        }}
        // SVGs come from our own Figma export.
        dangerouslySetInnerHTML={
          svg ? { __html: svg.replace(/<svg /, '<svg style="max-width:48px;max-height:48px" ') } : undefined
        }
      >
        {svg ? undefined : <span style={muted}>—</span>}
      </div>
      <div style={{ fontSize: 13 }}>{icon.name.split('/').pop()}</div>
      {icon.code[0] && (
        <code style={{ ...mono, fontSize: 11, color: 'var(--color-text-secondary)' }}>{icon.code[0]}</code>
      )}
    </div>
  );
}

function IconsPage({ brand, theme }: { brand: string; theme: string }) {
  const [query, setQuery] = useState('');
  if (!icons.length)
    return (
      <Page>
        <p>
          No icons exported yet. Run <code style={mono}>FIGMA_TOKEN=… npm run export:icons</code> or the{' '}
          <b>Export icons</b> GitHub Action.
        </p>
      </Page>
    );
  const q = query.trim().toLowerCase();
  const shown = icons.filter(i => !q || [i.name, ...i.code, ...i.aliases].some(s => s.toLowerCase().includes(q)));
  const sections = [...new Set(shown.map(i => i.section ?? 'Other'))];
  return (
    <Page>
      <input
        value={query}
        onChange={e => setQuery(e.target.value)}
        placeholder="Search by Figma name, code name or old name"
        style={{ padding: '10px 12px', fontSize: 14, borderRadius: 8, border: '1px solid var(--color-border-primary)' }}
      />
      {sections.map(section => (
        <Section key={section} title={section}>
          <div className="ds-cards" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))' }}>
            {shown
              .filter(i => (i.section ?? 'Other') === section)
              .map(i => (
                <IconCard key={i.name} icon={i} brand={brand} theme={theme} />
              ))}
          </div>
        </Section>
      ))}
    </Page>
  );
}

export const AllIcons: Story = {
  name: 'All icons',
  render: (_, { globals }) => <IconsPage brand={globals.brand} theme={globals.theme} />,
};
