import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { mono } from './tokens';

/** Library page used by Icons.stories.tsx and Illustrations.stories.tsx. */
export type LibraryKind = 'icons' | 'illustrations';

/** Shape written by scripts/export-icons.mjs. */
interface IconSet {
  name: string;
  section?: string;
  code: string[];
  aliases: string[];
  note?: string;
  color?: { figma: string; css: string };
  files: ({ file: string } & Record<string, string>)[];
}

/** One tile: a set, or one option of a set (e.g. Chevron · Up, Zodiac · Aries). */
interface Icon {
  id: string;
  name: string;
  group?: string;
  section: string;
  code: string[];
  tags: string[];
  note?: string;
  color?: IconSet['color'];
  files: IconSet['files'];
}

// Generated by `npm run export:icons`; empty until the first export.
const manifests = import.meta.glob<IconSet[]>('../icons/icons.json', { eager: true, import: 'default' });
const svgs = import.meta.glob<string>('../icons/**/*.svg', { eager: true, query: '?raw', import: 'default' });

const BRAND_NAMES: Record<string, string> = {
  'purple-garden': 'Purple Garden',
  kasamba: 'Kasamba',
  psiquicos: 'Psiquicos',
  'purple-ocean': 'Purple Ocean',
};
const SECTION_ORDER = [
  'Navigation',
  'UI Actions',
  'Communication & Media',
  'Status & feedback',
  'Spiritual Content',
  'Reading Categories',
  'Brands & Social',
  'Payment methods',
  'Flags',
  'Empty States',
];

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const fileBase = (file?: string) =>
  file
    ?.split('/')
    .pop()
    ?.replace(/(-dark)?\.svg$/, '');

/** Split sets with an option property (Direction, Sign, Country…) into one tile per option. */
function toIcons(sets: IconSet[]): Icon[] {
  return sets.flatMap(set => {
    const optionKey = Object.keys(set.files[0] ?? {}).find(k => !['file', 'Brand', 'Theme'].includes(k));
    const options = optionKey ? [...new Set(set.files.map(f => f[optionKey]))] : [undefined];
    const parts = set.name.split('/').map(s => s.trim());
    const group = parts.length > 1 ? parts[0] : undefined;
    const leaf = parts[parts.length - 1];
    return options.map(option => {
      const files = option ? set.files.filter(f => f[optionKey!] === option) : set.files;
      // An option's own code name is the one its exported file is named after (chevron-up.svg → chevronUp).
      const own = option ? set.code.filter(c => kebab(c) === fileBase(files[0]?.file)) : set.code;
      return {
        id: option ? `${set.name}|${option}` : set.name,
        // Plural sets (Flags, Press) read better as just the option: "argentina", not "flags argentina".
        name: option ? (/s$/i.test(leaf) ? option : `${leaf} ${option}`) : leaf,
        group,
        section: set.section ?? 'Other',
        code: own,
        tags: [...set.aliases, ...(group ? [group] : [])],
        note: set.note,
        color: set.color,
        files,
      };
    });
  });
}

const ICONS = toIcons(Object.values(manifests)[0] ?? []);

/** Figma sections that hold illustrations rather than icons. */
const ILLUSTRATION_SECTIONS = ['Reading Categories', 'Empty States'];
const kindOf = (i: Icon): LibraryKind => (ILLUSTRATION_SECTIONS.includes(i.section) ? 'illustrations' : 'icons');

function variantFor(icon: Icon, brand: string, theme: string) {
  const forBrand = icon.files.filter(f => !f.Brand || f.Brand === BRAND_NAMES[brand]);
  return (
    forBrand.find(f => (f.Theme ?? 'Light').toLowerCase() === theme) ??
    forBrand.find(f => !f.Theme || f.Theme === 'Light')
  );
}

const svgFor = (file?: string) => (file ? svgs[`../icons/${file}`] : undefined);

/** Natural size from the SVG, to tell icons (24px) from illustrations. */
function naturalSize(svg?: string) {
  const m = svg?.match(/viewBox="[\d.-]+ [\d.-]+ ([\d.]+) ([\d.]+)"/);
  return m ? Math.max(+m[1], +m[2]) : 24;
}

function Svg({ svg, size, color }: { svg?: string; size: number; color?: string }) {
  // Exported SVGs reuse ids like "a"; make them unique per preview so embedded images don't swap.
  const uid = useId().replace(/:/g, '');
  if (!svg) return <span className="il-missing">Not in this brand</span>;
  const html = svg
    .replace(/\bid="([^"]+)"/g, `id="$1-${uid}"`)
    .replace(/url\(#([^)]+)\)/g, `url(#$1-${uid})`)
    .replace(/href="#([^"]+)"/g, `href="#$1-${uid}"`);
  return (
    <span
      className="il-svg"
      style={{ width: size, height: size, color: `var(${color ?? '--color-icon-primary'})` }}
      // SVGs come from our own Figma export.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

const CSS = `
.il { display: grid; grid-template-columns: minmax(0, 1fr) 260px; gap: 56px; padding: 48px; max-width: 1440px; margin: 0 auto;
  color: var(--color-text-primary); }
.il-nav { grid-column: 2; grid-row: 1; position: sticky; top: 24px; align-self: start; max-height: calc(100vh - 48px); overflow: auto;
  border-left: 1px solid var(--color-border-primary); padding: 4px 0 4px 0; }
.il-nav h4 { margin: 0 0 20px; padding-left: 20px; font-size: 18px; font-weight: 600; letter-spacing: .06em; text-transform: uppercase;
  color: var(--color-text-secondary); }
.il-nav a { display: flex; justify-content: space-between; gap: 8px; padding: 9px 16px 9px 20px; margin-left: -1px; border-left: 3px solid transparent;
  color: var(--color-text-primary); text-decoration: none; font-size: 16px; }
.il-nav a:hover { background: var(--color-background-secondary); }
.il-nav a span { color: var(--color-text-secondary); font-size: 12px; }
.il-nav a.on { border-left-color: var(--color-branding-primary); background: var(--color-background-secondary);
  color: var(--color-branding-primary); font-weight: 600; }
.il-head { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px;
  border-bottom: 1px solid var(--color-border-primary); padding-bottom: 24px; }
.il-head h1 { margin: 0; font-family: var(--font-family-title), system-ui; font-size: clamp(40px, 6vw, 72px); line-height: 1; }
.il-chip { padding: 8px 14px; border-radius: 999px; background: var(--color-background-secondary); font-size: 13px; white-space: nowrap; }
.il-lead { color: var(--color-text-secondary); font-size: 17px; margin: 24px 0 32px; }
.il-main { grid-column: 1; grid-row: 1; min-width: 0; }
.il-searchbar { position: sticky; top: 0; z-index: 2; padding: 16px 0; background: var(--color-background-primary); }
.il-search { display: flex; align-items: center; gap: 12px; width: 100%; padding: 14px 20px;
  border: 1px solid var(--color-border-primary); border-radius: 999px; background: var(--color-background-primary); }
.il-search:focus-within { border-color: var(--color-branding-primary); }
.il-search input { border: 0; outline: 0; flex: 1; font: inherit; font-size: 17px; background: transparent; color: inherit; }
.il-section { scroll-margin-top: 96px; margin-top: 40px; }
.il-section h2 { margin: 0 0 24px; padding-bottom: 16px; border-bottom: 1px solid var(--color-border-primary);
  font-family: var(--font-family-title), system-ui; font-size: 32px; }
.il-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 16px; }
.il-grid.xl { grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 20px; }
.il-stage.xl { height: 320px; }
.il-tile { aspect-ratio: 1; display: grid; place-items: center; align-content: center; gap: 12px; padding: 12px; border: 0;
  border-radius: 24px; background: var(--color-background-secondary); cursor: pointer; font: inherit; color: inherit;
  transition: transform .15s, box-shadow .15s; }
.il-tile:hover, .il-tile:focus-visible { transform: translateY(-2px); box-shadow: 0 6px 20px rgb(0 0 0 / .08); outline: none; }
.il-tile small { color: var(--color-text-secondary); font-size: 13px; text-align: center; line-height: 1.3; }
.il-svg { display: inline-grid; place-items: center; }
.il-svg svg { width: 100%; height: 100%; }
.il-missing { color: var(--color-text-secondary); font-size: 12px; }
.il-empty { color: var(--color-text-secondary); margin-top: 48px; }
.il-overlay { position: fixed; inset: 0; background: rgb(0 0 0 / .45); display: grid; place-items: center; padding: 24px; z-index: 10; }
.il-modal { width: min(620px, 100%); max-height: calc(100vh - 48px); overflow: auto; border-radius: 32px;
  background: var(--color-background-primary); color: var(--color-text-primary); box-shadow: 0 24px 64px rgb(0 0 0 / .25); }
.il-modal header { display: flex; justify-content: space-between; align-items: flex-start; padding: 32px 40px 20px;
  border-bottom: 1px solid var(--color-border-primary); }
.il-modal header p { margin: 0; color: var(--color-text-secondary); font-size: 14px; }
.il-modal header h3 { margin: 4px 0 0; font-family: var(--font-family-title), system-ui; font-size: 30px; }
.il-close { width: 40px; height: 40px; border-radius: 50%; border: 0; background: var(--color-background-secondary); cursor: pointer;
  font-size: 22px; color: inherit; }
.il-body { padding: 24px 40px 36px; display: grid; gap: 28px; }
.il-row { display: flex; align-items: center; gap: 12px; flex-wrap: wrap; }
.il-row b { font-size: 17px; margin-right: 8px; }
.il-size { min-width: 44px; padding: 8px 10px; border-radius: 10px; border: 1px solid var(--color-border-primary);
  background: var(--color-background-primary); cursor: pointer; font: inherit; color: inherit; }
.il-size.on { outline: 2px solid var(--color-text-primary); outline-offset: -1px; }
.il-stage { height: 240px; display: grid; place-items: center; border-radius: 24px; border: 1px solid var(--color-border-primary);
  background: radial-gradient(var(--color-border-primary) 1px, transparent 1px) 0 0 / 14px 14px, var(--color-background-secondary); }
.il-brands { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px; }
.il-brands div { display: grid; justify-items: center; align-content: center; gap: 8px; min-height: 96px; padding: 14px 6px;
  border-radius: 16px; background: var(--color-background-secondary); font-size: 12px; color: var(--color-text-secondary); text-align: center; }
.il-meta { display: grid; grid-template-columns: max-content minmax(0, 1fr); gap: 10px 16px; margin: 0; font-size: 14px; }
.il-meta dt { color: var(--color-text-secondary); }
.il-meta dd { margin: 0; overflow-wrap: anywhere; }
.il-copy { border: 0; background: none; color: var(--color-branding-primary); cursor: pointer; font: inherit; font-size: 13px; padding: 0 0 0 8px; }
.il-modal h4 { margin: 0 0 12px; font-size: 19px; }
.il-related { display: grid; grid-template-columns: repeat(auto-fill, minmax(110px, 1fr)); gap: 10px; }
.il-related .il-tile { border-radius: 18px; gap: 8px; }
.il-tags { display: flex; flex-wrap: wrap; gap: 8px; }
.il-tags button { padding: 7px 14px; border-radius: 999px; border: 0; background: var(--color-background-secondary); cursor: pointer;
  font: inherit; font-size: 13px; color: inherit; }
@media (max-width: 767px) {
  .il { grid-template-columns: minmax(0, 1fr); padding: 24px 16px; gap: 0; }
  .il-nav { display: none; }
  .il-grid { grid-template-columns: repeat(auto-fill, minmax(110px, 1fr)); gap: 10px; }
  .il-tile { border-radius: 18px; }
  .il-modal header, .il-body { padding-left: 20px; padding-right: 20px; }
  .il-brands { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
`;

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

function Tile(props: { icon: Icon; brand: string; theme: string; onOpen: () => void; size?: number }) {
  const { icon, brand, theme, onOpen, size = 24 } = props;
  const svg = svgFor(variantFor(icon, brand, theme)?.file);
  const big = naturalSize(svg) > 32;
  return (
    <button className="il-tile" onClick={onOpen} title={[...icon.code, ...icon.tags].join(', ')}>
      <Svg svg={svg} size={big ? size * 3 : size} color={icon.color?.css} />
      <small>{icon.name.toLowerCase()}</small>
    </button>
  );
}

function Detail(props: {
  icon: Icon;
  brand: string;
  theme: string;
  onClose: () => void;
  onOpen: (i: Icon) => void;
  onTag: (t: string) => void;
}) {
  const { icon, brand, theme, onClose, onOpen, onTag } = props;
  const variant = variantFor(icon, brand, theme);
  const svg = svgFor(variant?.file);
  const big = naturalSize(svg) > 32;
  const sizes = big ? [96, 184, 256] : [16, 20, 24, 32, 48];
  const [size, setSize] = useState(big ? 184 : 24);
  const [copied, setCopied] = useState('');
  useEffect(() => setSize(big ? 184 : 24), [icon.id, big]);
  useEffect(() => {
    const esc = (e: KeyboardEvent) => e.key === 'Escape' && onClose();
    window.addEventListener('keydown', esc);
    return () => window.removeEventListener('keydown', esc);
  }, [onClose]);
  const related = ICONS.filter(
    i =>
      i.id !== icon.id &&
      kindOf(i) === kindOf(icon) &&
      (icon.group ? i.group === icon.group : i.section === icon.section),
  ).slice(0, 8);
  const copy = (text: string) => {
    navigator.clipboard?.writeText(text);
    setCopied(text);
    setTimeout(() => setCopied(''), 1200);
  };
  const CopyButton = ({ text }: { text: string }) => (
    <button className="il-copy" onClick={() => copy(text)}>
      {copied === text ? 'Copied' : 'Copy'}
    </button>
  );
  return (
    <div className="il-overlay" onClick={onClose}>
      <div className="il-modal" role="dialog" aria-label={icon.name} onClick={e => e.stopPropagation()}>
        <header>
          <div>
            <p>{[icon.section, icon.group].filter(Boolean).join(' · ')}</p>
            <h3>{icon.name.toLowerCase()}</h3>
          </div>
          <button className="il-close" onClick={onClose} aria-label="Close">
            ×
          </button>
        </header>
        <div className="il-body">
          <div className="il-row">
            <b>Size</b>
            {sizes.map(s => (
              <button key={s} className={`il-size${s === size ? ' on' : ''}`} onClick={() => setSize(s)}>
                {s}
              </button>
            ))}
          </div>
          <div className={`il-stage${big ? ' xl' : ''}`}>
            <Svg svg={svg} size={size} color={icon.color?.css} />
          </div>
          <div>
            <h4>Brands</h4>
            <div className="il-brands">
              {Object.entries(BRAND_NAMES).map(([key, label]) => (
                <div key={key}>
                  <Svg svg={svgFor(variantFor(icon, key, theme)?.file)} size={big ? 64 : 24} color={icon.color?.css} />
                  {label}
                </div>
              ))}
            </div>
          </div>
          <dl className="il-meta">
            <dt>Code</dt>
            <dd>
              {icon.code.length ? (
                icon.code.map(c => (
                  <span key={c} style={{ ...mono, marginRight: 12 }}>
                    {c}
                    <CopyButton text={c} />
                  </span>
                ))
              ) : (
                <span style={{ color: 'var(--color-text-secondary)' }}>Figma only – not in code yet</span>
              )}
            </dd>
            {variant && (
              <>
                <dt>File</dt>
                <dd style={mono}>
                  icons/{variant.file}
                  <CopyButton text={`icons/${variant.file}`} />
                </dd>
              </>
            )}
            <dt>Colour</dt>
            <dd style={mono}>{icon.color ? `${icon.color.css} (${icon.color.figma})` : 'Own colours'}</dd>
            {icon.note && (
              <>
                <dt>Note</dt>
                <dd>{icon.note}</dd>
              </>
            )}
          </dl>
          {related.length > 0 && (
            <div>
              <h4>Related icons</h4>
              <div className="il-related">
                {related.map(r => (
                  <Tile key={r.id} icon={r} brand={brand} theme={theme} onOpen={() => onOpen(r)} size={20} />
                ))}
              </div>
            </div>
          )}
          {icon.tags.length > 0 && (
            <div>
              <h4>Tags</h4>
              <div className="il-tags">
                {icon.tags.map(t => (
                  <button key={t} onClick={() => onTag(t)}>
                    {t.toLowerCase()}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export function IconLibrary({ brand, theme, kind }: { brand: string; theme: string; kind: LibraryKind }) {
  const items = useMemo(() => ICONS.filter(i => kindOf(i) === kind), [kind]);
  const noun = kind === 'icons' ? 'icon' : 'illustration';
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState<Icon | null>(null);
  const [active, setActive] = useState('');
  const root = useRef<HTMLDivElement>(null);

  const q = query.trim().toLowerCase();
  const shown = useMemo(
    () => items.filter(i => !q || [i.name, i.group ?? '', ...i.code, ...i.tags].some(s => s.toLowerCase().includes(q))),
    [q, items],
  );
  const sections = useMemo(() => {
    const rank = (s: string) => SECTION_ORDER.indexOf(s) + 1 || 99;
    return [...new Set(shown.map(i => i.section))].sort((a, b) => rank(a) - rank(b));
  }, [shown]);

  // Highlight the section currently in view in the side menu.
  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => {
        const top = entries
          .filter(e => e.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top)[0];
        if (top) setActive(top.target.id);
      },
      { rootMargin: '0px 0px -70% 0px' },
    );
    root.current?.querySelectorAll('.il-section').forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, [sections]);

  if (!items.length)
    return (
      <div className="il">
        <style>{CSS}</style>
        <p className="il-empty">
          No icons exported yet. Run the <b>Export icons</b> GitHub Action or{' '}
          <code style={mono}>npm run export:icons</code>.
        </p>
      </div>
    );

  return (
    <div className="il" ref={root}>
      <style>{CSS}</style>
      <nav className="il-nav" aria-label="Icon sections">
        <h4>Content</h4>
        {sections.map(s => (
          <a
            key={s}
            href={`#${slug(s)}`}
            className={active === slug(s) ? 'on' : ''}
            onClick={e => {
              e.preventDefault();
              document.getElementById(slug(s))?.scrollIntoView({ behavior: 'smooth' });
            }}
          >
            {s} <span>{shown.filter(i => i.section === s).length}</span>
          </a>
        ))}
      </nav>
      <main className="il-main">
        <div className="il-head">
          <h1>{kind === 'icons' ? 'Icon library' : 'Illustrations'}</h1>
          <span className="il-chip">
            {items.length} {noun}s
          </span>
        </div>
        <p className="il-lead">
          Every {noun} from the Figma DS-Foundation file, shown for <b>{BRAND_NAMES[brand]}</b> in {theme} mode. Switch
          brand and theme in the toolbar; click any {noun} for sizes, code name and tags.
        </p>
        <div className="il-searchbar">
          <label className="il-search">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="11" cy="11" r="7" />
              <path d="m20 20-4-4" />
            </svg>
            <input
              value={query}
              onChange={e => setQuery(e.target.value)}
              placeholder={`Search ${noun}s by name, code name or keyword…`}
              aria-label={`Search ${noun}s`}
            />
          </label>
        </div>
        {!shown.length && <p className="il-empty">No icons match “{query}”.</p>}
        {sections.map(s => (
          <section key={s} id={slug(s)} className="il-section">
            <h2>{s}</h2>
            <div className={`il-grid${kind === 'illustrations' ? ' xl' : ''}`}>
              {shown
                .filter(i => i.section === s)
                .map(i => (
                  <Tile
                    key={i.id}
                    icon={i}
                    brand={brand}
                    theme={theme}
                    onOpen={() => setOpen(i)}
                    size={kind === 'illustrations' ? 56 : 24}
                  />
                ))}
            </div>
          </section>
        ))}
      </main>
      {open && (
        <Detail
          icon={open}
          brand={brand}
          theme={theme}
          onClose={() => setOpen(null)}
          onOpen={setOpen}
          onTag={t => {
            setQuery(t);
            setOpen(null);
          }}
        />
      )}
    </div>
  );
}
